name: flow_app
# Display name for app stores and launchers is configured per-platform.
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  
  # Other dependencies
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  fl_chart: ^0.66.0
  circular_countdown_timer: ^0.2.3
  audioplayers: ^6.5.0
  path_provider: ^2.0.11
  http: ^1.1.0
  file_selector: ^1.0.4
  mime: ^1.0.2
  image_picker: ^0.8.7
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^19.4.2
  permission_handler: ^11.3.0
  # Removed flutter_foreground_task due to Gradle/namespace compatibility issues in some setups.
  # If you need a foreground service, consider adding a compatible package or pinning a
  # specific version that matches your Android Gradle Plugin.

  # Ensure the linux implementation is available to avoid build-time warnings on desktop:
  flutter_local_notifications_linux: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/flow_2.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/flow_2.png"
  windows:
    generate: true
    image_path: "assets/flow_2.png"
  macos:
    generate: true
    image_path: "assets/flow_2.png"


flutter:
  uses-material-design: true
  assets:
    - assets/

