// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzttjAUWsJYSej2l0tHd48WgjT47N2vw',
    appId: '1:38975844667:web:ea9c74833673ac7ac6071e',
    messagingSenderId: '38975844667',
    projectId: 'flow-931a7',
    authDomain: 'flow-931a7.firebaseapp.com',
    storageBucket: 'flow-931a7.firebasestorage.app',
    measurementId: 'G-8ME06H3N7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9M51toY1A-sK5OeCWOll8Q9HJvu2Q8sE',
    appId: '1:38975844667:android:e6fc68a9a8499e45c6071e',
    messagingSenderId: '38975844667',
    projectId: 'flow-931a7',
    storageBucket: 'flow-931a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBNqHmHjzLYPFuO9v4umrYNdMdaktsdY',
    appId: '1:38975844667:ios:e201cb5f90c45190c6071e',
    messagingSenderId: '38975844667',
    projectId: 'flow-931a7',
    storageBucket: 'flow-931a7.firebasestorage.app',
    iosBundleId: 'com.example.flowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBNqHmHjzLYPFuO9v4umrYNdMdaktsdY',
    appId: '1:38975844667:ios:e201cb5f90c45190c6071e',
    messagingSenderId: '38975844667',
    projectId: 'flow-931a7',
    storageBucket: 'flow-931a7.firebasestorage.app',
    iosBundleId: 'com.example.flowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLzttjAUWsJYSej2l0tHd48WgjT47N2vw',
    appId: '1:38975844667:web:3653a27e0d47e9b5c6071e',
    messagingSenderId: '38975844667',
    projectId: 'flow-931a7',
    authDomain: 'flow-931a7.firebaseapp.com',
    storageBucket: 'flow-931a7.firebasestorage.app',
    measurementId: 'G-HDPYBBB99J',
  );
}
